name: darttonconnect
description: Dart SDK for TON Connect. Use it to connect your app to TON wallets via TonConnect protocol.
version: 1.0.3
homepage: https://github.com/romanovichim/dartTonconnect

environment:
  sdk: '>=2.18.4 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.2
  hex: ^0.2.0
  http: '>=0.13.5 <=1.1.0'
  logger: ^1.3.0
  pinenacl: ^0.5.1
  universal_html: ^2.2.1
  shared_preferences: ^2.1.2
